services:
  3xui-shopbot:
    build: .
    command: sh -c "if [ -f src/shop_bot/__main__.py ]; then exec python3 src/shop_bot/__main__.py; elif [ -f shop_bot/__main__.py ]; then exec python3 shop_bot/__main__.py; else exec python3 -m shop_bot.__main__; fi"
    restart: unless-stopped
    ports:
      - '1488:1488'
    volumes:
      - .:/app/project
    container_name: 3xui-shopbot
